version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Instalando cli de nestjs"
      - npm install -g @nestjs/cli
  build:
    commands:
      - echo "Instalando dependencia de la aplicacion"
      - npm install
      - echo "Ejecutando pruebas"
      - npm run test
      - echo "Construyendo el build"
      - npm run build

artifacts:
  files:
    - '**/*'