version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands: 
      - echo "Instalar cli nestjs"
      - npm install -g @nestjs/cli
  build: 
    commands:
      - echo "Instalando dependencias la aplicacion"
      - npm install
      - echo "Validar pruebas unitarias"
      - npm run test
      - echo "Construyendo el build"
      - npm run build
  post_build:
    commands:
      - echo "Empaquetando nuestra aplicacion"

artifacts:
  files: 
    - '**/*'