version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands: 
      - echo "Instalando pnpm"
      - npm install -g pnpm
      - echo "Instalar cli nestjs"
      - npm install -g @nestjs/cli
  build: 
    commands:
      - echo "Instalando dependencias la aplicacion"
      - pnpm install
      - echo "Validar pruebas unitarias"
      - pnpm run test
      - echo "Construyendo el build"
      - pnpm run build
  post_build:
    commands:
      - echo ""
      - zip -r deploy/app.zip . -x "node_modules/*"

artifacts:
  files: deploy/app.zip